### ISSUE TITLE
husky precommit

### ISSUE THREAD

**Issue by f1eeman** [logue/vite-vuetify-ts-starter#6]
vscode;
actual version for this template;

I added the component to the "components" directory, then imported it into homePage.vue. Tried to commit but got the following errors:
1)Could not find "stylelint-config-prettier"
2) problems with catalog node_modules.

your styleling.config:

```
customSyntax: postcss-html
extends:
  - stylelint-config-html/vue
  - stylelint-config-recommended-scss
  - stylelint-config-recommended-vue/scss
  - stylelint-config-prettier
plugins:
  - stylelint-order
  - stylelint-scss
ignoreFiles:
  - 'dist/**/*'
rules:
  color-function-notation: legacy
  function-no-unknown: null
  no-descending-specificity: null
  scss/no-global-function-names: null
```

![image](https://user-images.githubusercontent.com/49826703/203551576-1183b1db-b304-46c0-b4cd-4848d4fbc6d2.png)
